/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        pretendard: ["Pretendard", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
      },
      colors: {
        primary: {
          100: "rgb(var(--primary-100) / <alpha-value>)",
          90: "rgb(var(--primary-90) / <alpha-value>)",
          80: "rgb(var(--primary-80) / <alpha-value>)",
          70: "rgb(var(--primary-70) / <alpha-value>)",
          60: "rgb(var(--primary-60) / <alpha-value>)",
          50: "rgb(var(--primary-50) / <alpha-value>)",
          40: "rgb(var(--primary-40) / <alpha-value>)",
          30: "rgb(var(--primary-30) / <alpha-value>)",
          20: "rgb(var(--primary-20) / <alpha-value>)",
          10: "rgb(var(--primary-10) / <alpha-value>)",
        },
        secondary: {
          100: "rgb(var(--secondary-100) / <alpha-value>)",
          90: "rgb(var(--secondary-90) / <alpha-value>)",
          80: "rgb(var(--secondary-80) / <alpha-value>)",
          70: "rgb(var(--secondary-70) / <alpha-value>)",
          60: "rgb(var(--secondary-60) / <alpha-value>)",
          50: "rgb(var(--secondary-50) / <alpha-value>)",
          40: "rgb(var(--secondary-40) / <alpha-value>)",
          30: "rgb(var(--secondary-30) / <alpha-value>)",
          20: "rgb(var(--secondary-20) / <alpha-value>)",
          10: "rgb(var(--secondary-10) / <alpha-value>)",
        },
        system: {
          red: {
            100: "rgb(var(--system-red-100) / <alpha-value>)",
            90: "rgb(var(--system-red-90) / <alpha-value>)",
            80: "rgb(var(--system-red-80) / <alpha-value>)",
            70: "rgb(var(--system-red-70) / <alpha-value>)",
            60: "rgb(var(--system-red-60) / <alpha-value>)",
            50: "rgb(var(--system-red-50) / <alpha-value>)",
            40: "rgb(var(--system-red-40) / <alpha-value>)",
            30: "rgb(var(--system-red-30) / <alpha-value>)",
            20: "rgb(var(--system-red-20) / <alpha-value>)",
            10: "rgb(var(--system-red-10) / <alpha-value>)",
          },
          yellow: {
            100: "rgb(var(--system-yellow-100) / <alpha-value>)",
            90: "rgb(var(--system-yellow-90) / <alpha-value>)",
            80: "rgb(var(--system-yellow-80) / <alpha-value>)",
            70: "rgb(var(--system-yellow-70) / <alpha-value>)",
            60: "rgb(var(--system-yellow-60) / <alpha-value>)",
            50: "rgb(var(--system-yellow-50) / <alpha-value>)",
            40: "rgb(var(--system-yellow-40) / <alpha-value>)",
            30: "rgb(var(--system-yellow-30) / <alpha-value>)",
            20: "rgb(var(--system-yellow-20) / <alpha-value>)",
            10: "rgb(var(--system-yellow-10) / <alpha-value>)",
          },
          green: {
            100: "rgb(var(--system-green-100) / <alpha-value>)",
            90: "rgb(var(--system-green-90) / <alpha-value>)",
            80: "rgb(var(--system-green-80) / <alpha-value>)",
            70: "rgb(var(--system-green-70) / <alpha-value>)",
            60: "rgb(var(--system-green-60) / <alpha-value>)",
            50: "rgb(var(--system-green-50) / <alpha-value>)",
            40: "rgb(var(--system-green-40) / <alpha-value>)",
            30: "rgb(var(--system-green-30) / <alpha-value>)",
            20: "rgb(var(--system-green-20) / <alpha-value>)",
            10: "rgb(var(--system-green-10) / <alpha-value>)",
          },
          blue: {
            100: "rgb(var(--system-blue-100) / <alpha-value>)",
            90: "rgb(var(--system-blue-90) / <alpha-value>)",
            80: "rgb(var(--system-blue-80) / <alpha-value>)",
            70: "rgb(var(--system-blue-70) / <alpha-value>)",
            60: "rgb(var(--system-blue-60) / <alpha-value>)",
            50: "rgb(var(--system-blue-50) / <alpha-value>)",
            40: "rgb(var(--system-blue-40) / <alpha-value>)",
            30: "rgb(var(--system-blue-30) / <alpha-value>)",
            20: "rgb(var(--system-blue-20) / <alpha-value>)",
            10: "rgb(var(--system-blue-10) / <alpha-value>)",
          },
        },
        gray: {
          black: "rgb(var(--gray-black) / <alpha-value>)",
          100: "rgb(var(--gray-100) / <alpha-value>)",
          95: "rgb(var(--gray-95) / <alpha-value>)",
          90: "rgb(var(--gray-90) / <alpha-value>)",
          80: "rgb(var(--gray-80) / <alpha-value>)",
          70: "rgb(var(--gray-70) / <alpha-value>)",
          60: "rgb(var(--gray-60) / <alpha-value>)",
          50: "rgb(var(--gray-50) / <alpha-value>)",
          40: "rgb(var(--gray-40) / <alpha-value>)",
          30: "rgb(var(--gray-30) / <alpha-value>)",
          20: "rgb(var(--gray-20) / <alpha-value>)",
          10: "rgb(var(--gray-10) / <alpha-value>)",
          5: "rgb(var(--gray-5) / <alpha-value>)",
          white: "rgb(var(--gray-white) / <alpha-value>)",
        },
      },
      backgroundImage: {
        "gradient-button-fill-radial": "var(--gradient-button-fill-radial)",
        "gradient-button-right": "var(--gradient-button-right-gradient)",
        "gradient-button-left": "var(--gradient-button-left-gradient)",
        "gradient-header": "var(--gradient-header-bg)",
      },
    },
  },
  plugins: [],
};
